project_id = "pzfrcknnqjkqhmupprsi"

[functions.emit-nfe]
verify_jwt = false

[functions.check-nfe-status]
verify_jwt = false

[functions.generate-clinic-report]
verify_jwt = false

[functions.gamification-suggestions]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.ai-generate-image]
verify_jwt = false