#!/usr/bin/env sh

msg_file="$1"
msg="$(cat "$msg_file")"

case "$msg" in
  lovable:*)
    exit 0
    ;;
  *)
    echo "Erro: commit deve iniciar com 'lovable:'"
    echo "Use: npm run commit:lovable -- <mensagem>"
    exit 1
    ;;
esac
